FILENAME = ISL_solutions

$(FILENAME).pdf: $(FILENAME).tex

#compiling twice for autogenerated lists
	-pdflatex -interaction=nonstopmode $(FILENAME).tex
	-pdflatex -interaction=nonstopmode $(FILENAME).tex

#removing autogenerated stuff
	rm -f *.aux
	rm -f *.log
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
	rm -f *.synctex.gz

clean:
	rm -r $(FILENAME).pdf

.PHONY: clean
