TEMPFILES = \
	*.aux \
	*.lo[g,f,t] \
	*.out \
	*.toc \
	*.syntex.gz \
	*.gnuplot \
	*.table \

FILENAME = ISL_solutions

$(FILENAME).pdf: $(FILENAME).tex

#compiling twice for autogenerated lists
	-pdflatex --enable-write18 $(FILENAME).tex
	-pdflatex -interaction=nonstopmode $(FILENAME).tex
	rm -f $(TEMPFILES)

clean:
	rm -r $(FILENAME).pdf

.PHONY: clean
